[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://frabjous-marshmallow-44817e.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
